package ca.sheridan.wrimicha.model;

import lombok.*;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@RequiredArgsConstructor
public class Team implements Serializable{

    private Long id;  // auto increment to be generated by RDBMS
    @NonNull
    private  String country;
    @NonNull
    private  String continent;
    @NonNull
    private int gamesPlayed;
    @NonNull
    private int gamesWon;
    @NonNull
    private int gamesDrawn;
    @NonNull
    private int gamesLost;
}
